trigger:
  branches:
    include:
    - main
    - dev

pr: none

variables:
  - group: SomeVariableGroup

stages:
- stage: prod
  displayName: prod
  condition: eq(variables['build.sourceBranchName'], 'main'))
  jobs:
  - job: Deploy_ZBEE_SERVER
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
    - script: |
        echo working
    - script: |
        echo working
        
- stage: dev
  displayName: dev
  condition: eq(variables['build.sourceBranchName'], 'dev'))
  jobs:
  - job: Deploy_ZBEE_SERVER
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
    - script: |
        echo "//registry.npmjs.org/:_authToken=$(NPM-TOKEN)" > ~/.npmrc
        npm -g install yarn
      displayName: "settings"
    - script: |
        export AWS_ACCESS_KEY_ID=$(AWS-ACCESS-KEY-ID-PROD)
        export AWS_SECRET_ACCESS_KEY=$(AWS-SECRET-ACCESS-KEY-PROD)
        export AWS_DEFAULT_REGION="ap-northeast-2"
        cd zbee-server
        cp ci/serverless.yml ./
        yarn
        yarn build
        yarn deploy dev
        
