trigger:
  branches:
    include:
    - master
    - dev

pr: none

variables:
  - group: SomeVariableGroup
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}
    stageName: prod
  ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}
    stageName: dev

jobs:
- job: Deploy_ZBEE_SERVER
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
  - script: |
      echo ${SOME_KEY}